# -*- coding: utf-8 -*-
"""Churn_Terbaru.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/158TzpOfesZ5FXpNjNOjVEfiL8HtTWdFt

##**BAGIAN 1**
**PENDAHULUAN & KONTEKS BISNIS**

**1.1 LATAR BELAKANG MASALAH**

Customer churn (perpindahan pelanggan) didefinisikan sebagai fenomena
dimana pelanggan berhenti menggunakan produk atau layanan suatu perusahaan.
Dalam konteks e-commerce, churn terjadi ketika pelanggan yang sebelumnya
aktif bertransaksi tidak lagi melakukan pembelian dalam periode waktu
tertentu.

Fenomena churn menjadi tantangan kritis bagi industri e-commerce karena:

1. BIAYA AKUISISI vs RETENSI:
   Menurut penelitian Harvard Business Review, biaya untuk memperoleh
   pelanggan baru (customer acquisition cost) bisa 5-25x lebih mahal
   dibandingkan mempertahankan pelanggan yang sudah ada. Oleh karena itu,
   memprediksi dan mencegah churn jauh lebih efisien secara finansial.

2. DAMPAK TERHADAP REVENUE:
   Peningkatan retensi pelanggan sebesar 5% saja dapat meningkatkan
   profit perusahaan sebesar 25-95% (Bain & Company). Setiap pelanggan
   yang churn merepresentasikan hilangnya potensi pendapatan jangka panjang
   (Customer Lifetime Value / CLV).

3. EFEK DOMINO:
   Pelanggan yang churn tidak hanya berhenti bertransaksi, tetapi juga
   berpotensi memberikan review negatif dan mempengaruhi calon pelanggan
   lainnya (negative word-of-mouth), sehingga efek kerugiannya berlipat.

**1.2 PERAN EXPLAINABLE AI (XAI) DALAM PREDIKSI CHURN**

Meskipun model machine learning seperti XGBoost mampu memprediksi churn
dengan akurasi tinggi, model tersebut seringkali bersifat "black-box" —
artinya sulit untuk memahami MENGAPA model memberikan prediksi tertentu.

Di sinilah Explainable AI (XAI) berperan:
- XAI memberikan TRANSPARANSI terhadap proses pengambilan keputusan model
- Dengan SHAP (SHapley Additive exPlanations), kita dapat mengetahui
  FAKTOR APA saja yang paling berkontribusi terhadap prediksi churn
- Insight ini memungkinkan tim bisnis untuk merancang strategi retensi
  yang TARGETED dan efektif, bukan blanket approach

**1.3 TUJUAN PENELITIAN**

Penelitian ini bertujuan untuk:
1. Membangun model prediksi customer churn menggunakan algoritma XGBoost
   dengan performa tinggi (AUC, F1-Score, Accuracy)
2. Membandingkan performa XGBoost dengan model baseline (Logistic Regression)
   dan model ensemble lainnya (Random Forest)
3. Menganalisis faktor-faktor utama yang mendorong churn menggunakan
   pendekatan SHAP sebagai metode XAI
4. Memberikan rekomendasi bisnis yang actionable berdasarkan insight
   dari analisis XAI

**1.4 RUANG LINGKUP PENELITIAN**

- Data    : Dataset e-commerce yang terdiri dari 4 tabel (customer, product,
            click_stream, transactions) dengan total ~100.000 pelanggan
- Metode  : Supervised Learning (Binary Classification)
- Model   : Logistic Regression, Random Forest, XGBoost
- XAI     : SHAP (TreeExplainer)
- Target  : Churn = pelanggan tidak bertransaksi > 90 hari

**1.5 METODOLOGI PENELITIAN**

Penelitian mengikuti framework CRISP-DM (Cross Industry Standard Process
for Data Mining) dengan tahapan:

1. Business Understanding: Memahami masalah churn dan dampak bisnisnya.
2. Data Understanding: Mengumpulkan dan mengeksplorasi data dari 4 tabel.
3. Data Preparation: Melakukan cleaning, feature engineering, serta labeling churn.
4. Modeling: Melatih 3 model, yaitu Logistic Regression, Random Forest, dan XGBoost.
5. Evaluation: Melakukan perbandingan metrik serta cross validation.
6. Deployment (Insight): Melakukan analisis SHAP serta menyusun rekomendasi bisnis.

##**BAGIAN 2**
**PERSIAPAN ENVIRONMENT & IMPOR LIBRARY**

Pada tahap ini, kita mengimpor seluruh library yang diperlukan untuk
analisis data, pemodelan, dan visualisasi. Pemilihan library didasarkan
pada kebutuhan:

Data & Komputasi:
- pandas & numpy: manipulasi data tabular dan komputasi numerik

Visualisasi:
- matplotlib & seaborn: pembuatan grafik dan visualisasi statistik

Preprocessing & Evaluasi (scikit-learn):
- StandardScaler: standarisasi fitur agar berskala seragam
- train_test_split: pembagian data train-test dengan stratified sampling
- StratifiedKFold & cross_val_score: cross validation untuk validasi model
- classification_report, confusion_matrix, roc_auc_score, dll: metrik evaluasi

Algoritma Klasifikasi:
- LogisticRegression (scikit-learn): model linear baseline untuk klasifikasi
  biner; digunakan sebagai benchmark performa minimum
- RandomForestClassifier (scikit-learn): ensemble berbasis bagging yang
  membangun banyak pohon keputusan secara paralel; digunakan sebagai
  model pembanding
- XGBClassifier (xgboost): ensemble berbasis gradient boosting yang
  membangun pohon secara sekuensial, memperbaiki error pohon sebelumnya;
  dipilih sebagai model utama karena performa tinggi dan kompatibilitas SHAP

Explainable AI:
- shap: interpretasi model menggunakan SHAP values (Shapley Additive
  exPlanations) berbasis game theory
"""

import os
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings

# Install gdown jika belum ada (untuk download dari Google Drive)
!pip install -q gdown
import gdown

from datetime import datetime
from sklearn.model_selection import train_test_split, StratifiedKFold, cross_val_score
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import (
    classification_report, confusion_matrix,
    roc_auc_score, roc_curve, f1_score, accuracy_score,
    precision_score, recall_score
)
from xgboost import XGBClassifier
import shap

# Konfigurasi visualisasi
plt.rcParams['figure.figsize'] = (12, 6)
plt.rcParams['font.size'] = 12
sns.set_style('whitegrid')
warnings.filterwarnings('ignore')

print("✅ Semua library berhasil diimpor.")

"""##**BAGIAN 3**
**PENGUMPULAN DATA (DATA COLLECTION)**

Dataset yang digunakan berasal dari platform e-commerce dan terdiri dari
4 tabel relasional:
1. customer.csv      : Data profil pelanggan (100.000 records)
2. product.csv       : Data katalog produk  
3. click_stream.csv  : Data aktivitas browsing pelanggan (~12.8 juta records)
4. transactions.csv  : Data transaksi pembelian (852.584 records)

Sumber data: Kaggle — "Transactional E-Commerce Dataset" oleh bytadit

URL: https://www.kaggle.com/datasets/bytadit/transactional-ecommerce

Justifikasi pemilihan dataset:
- Mencakup data demografis, perilaku, dan transaksional
- Ukuran data cukup besar untuk menghasilkan model yang representatif
- Memungkinkan konstruksi fitur RFM (Recency, Frequency, Monetary)
"""

datasets_to_load = [
    {"filename": "click_stream.csv", "file_id": "1ledaK9Wlo01JfOfHsZWpxJ2SKzoFWgM4", "df_var_name": "df_click_stream"},
    {"filename": "customer.csv", "file_id": "1pdSH5yutfJeGYp8bE4lCjBnGT7gREMD6", "df_var_name": "df_customer"},
    {"filename": "product.csv", "file_id": "1VNmWoZwETJ8BG8Ra6mIcWm9otG3SqP9w", "df_var_name": "df_product"},
    {"filename": "transactions.csv", "file_id": "1uEHMFWTFQZIEcPMHDCE2LTXnv6eF_MeN", "df_var_name": "df_transactions"}
]

for dataset_info in datasets_to_load:
    filename = dataset_info["filename"]
    file_id = dataset_info["file_id"]
    df_var_name = dataset_info["df_var_name"]

    if not os.path.exists(filename):
        url = f"https://drive.google.com/uc?id={file_id}"
        print(f"Downloading {filename}...")
        gdown.download(url, filename, quiet=False)
    else:
        print(f"File {filename} already exists. Skipping download.")

    # Muat CSV ke dalam DataFrame dan tetapkan ke nama variabel yang ditentukan
    globals()[df_var_name] = pd.read_csv(filename, on_bad_lines='skip')
    print(f"Loaded {filename} into DataFrame '{df_var_name}'.")

print(f"\nJumlah data Customer     : {len(df_customer):,}")
print(f"Jumlah data Product      : {len(df_product):,}")
print(f"Jumlah data Click Stream : {len(df_click_stream):,}")
print(f"Jumlah data Transactions : {len(df_transactions):,}")

"""##**BAGIAN 4**
**PEMAHAMAN KUALITAS DATA AWAL (DATA QUALITY CHECK)**

Tahap ini bertujuan untuk mengecek kualitas dataset sebelum
dilakukan preprocessing. Fokus analisis meliputi:
- Struktur dan tipe data setiap tabel
- Analisis missing values

Tujuannya adalah memastikan apakah data memerlukan pembersihan khusus.
Analisis data (EDA) yang lebih mendalam secara visual akan dilakukan
setelah seluruh data digabungkan dan fitur-fitur baru (seperti umur,
RFM, durasi sesi) selesai diekstraksi, agar analisis lebih komprehensif.
"""

# 4.1 Struktur & Info Dasar Setiap Tabel

print("=" * 60)
print("4.1 STRUKTUR & INFO DASAR SETIAP TABEL")
print("=" * 60)

for name, df in [("Customer", df_customer), ("Transactions", df_transactions),
                  ("Click Stream", df_click_stream), ("Product", df_product)]:
    print(f"\n{'─'*40}")
    print(f"Tabel: {name}")
    print(f"Shape : {df.shape}")
    print(f"{'─'*40}")
    df.info()
    print()

# 4.2 Analisis Missing Values

"""
Analisis missing values penting untuk menentukan strategi penanganan
yang tepat. Kolom dengan missing values tinggi mungkin perlu dihapus,
sedangkan missing values rendah bisa diisi (imputation).
"""
print("\n" + "=" * 60)
print("4.2 ANALISIS MISSING VALUES")
print("=" * 60)

summary_of_missing_tables = [] # Collect summary for the journal request

for name, df in [("Customer", df_customer), ("Transactions", df_transactions),
                  ("Click Stream", df_click_stream), ("Product", df_product)]:
    print(f"\n📊 Head of Tabel {name}:")
    display(df.head())
    missing = df.isnull().sum()
    missing_pct = (missing / len(df) * 100).round(2)
    missing_info = pd.DataFrame({
        'Missing Count': missing,
        'Missing (%)': missing_pct
    })
    missing_info = missing_info[missing_info['Missing Count'] > 0]

    print(f"\n📊 Missing Values — Tabel {name}:")
    if len(missing_info) == 0:
        print("   ✅ Tidak ada missing values.")
    else:
        print(missing_info.to_string())
        # Store information for the summary requested by the user
        summary_of_missing_tables.append((name, missing_info))

# Visualisasi Missing Values (hanya tabel yang memiliki missing)
tables_for_plot = []
for name, df_original in [("Customer", df_customer), ("Transactions", df_transactions),
                          ("Click Stream", df_click_stream), ("Product", df_product)]:
    if df_original.isnull().any().any():
        tables_for_plot.append((name, df_original))

if tables_for_plot:
    n_tables = len(tables_for_plot)
    fig, axes = plt.subplots(1, n_tables, figsize=(6 * n_tables, 5))
    if n_tables == 1:
        axes = [axes]
    for ax, (name, df_original) in zip(axes, tables_for_plot):
        missing_cols = df_original.isnull().sum()
        missing_cols = missing_cols[missing_cols > 0].sort_values(ascending=True)
        missing_cols.plot(kind='barh', color='#e74c3c', ax=ax)
        ax.set_title(f'Missing Values\n{name}', fontsize=12, fontweight='bold')
        ax.set_xlabel('Jumlah Missing')
    plt.tight_layout()
    plt.show()
else:
    print("\n✅ Semua tabel tidak memiliki missing values signifikan.")


# New summary output as requested by the user
print("\n" + "=" * 60)
print("RINGKASAN MISSING VALUES UNTUK JURNAL")
print("=" * 60)
if summary_of_missing_tables:
    print(f"Tiga tabel yang teridentifikasi memiliki missing values adalah:")
    for name, info_df in summary_of_missing_tables:
        missing_columns = ', '.join([f'`{col}`' for col in info_df.index.tolist()])
        total_missing_count = info_df['Missing Count'].sum()
        print(f"- Tabel {name}: {missing_columns} (Total Missing: {total_missing_count:,})")
else:
    print("Tidak ada missing values yang terdeteksi di semua tabel.")

# 4.3 Analisis Duplikasi Data

print("\n" + "=" * 60)
print("4.3 ANALISIS DUPLIKASI DATA")
print("=" * 60)

for name, df, pk_col in [
    ("Customer", df_customer, 'customer_id'),
    ("Transactions", df_transactions, 'booking_id'),
    ("Click Stream", df_click_stream, 'event_id'),
    ("Product", df_product, 'id')
]:
    print(f"\n📊 Tabel: {name}")
    # Cek duplikat berdasarkan semua kolom
    all_duplicates = df.duplicated().sum()
    if all_duplicates > 0:
        print(f"   ⚠️ Duplikat baris (semua kolom): {all_duplicates:,}")
    else:
        print("   ✅ Tidak ada duplikat baris (semua kolom).")

    # Cek duplikat berdasarkan Primary Key (jika ada)
    if pk_col:
        pk_duplicates = df.duplicated(subset=[pk_col]).sum()
        if pk_duplicates > 0:
            print(f"   ⚠️ Duplikat berdasarkan `{pk_col}`: {pk_duplicates:,}")
            # Contoh menampilkan baris duplikat berdasarkan PK
            # display(df[df.duplicated(subset=[pk_col], keep=False)].sort_values(by=pk_col).head())
        else:
            print(f"   ✅ Tidak ada duplikat berdasarkan `{pk_col}`.")

"""# Ringkasan Temuan Kualitas Data

Berdasarkan pengecekan data awal, ditemukan beberapa hal penting terkait pembersihan:

1. MISSING VALUES:
   - promo_code (Transactions): Memiliki missing values yang signifikan karena transaksi tanpa promo. Ini perlu ditangani dengan imputation (misal: diisi 'No Promo').
   - event_metadata (Click Stream): Memiliki missing values tinggi, namun karena kolom ini berisi JSON/teks detail yang tidak diagregasi untuk pemodelan sentral (hanya menggunakan agregasi event-level sederhana), kolom ini akan diabaikan tanpa di-impute.
   - Tabel Product (usage, season, baseColour, dll.): Meskipun terdapat missing values, tabel product secara keseluruhan tidak digabungkan dalam pipeline fitur utama (model lebih fokus pada perilaku interaksi & RFM), sehingga missing values-nya otomatis terabaikan.
   
2. TIPE DATA:
   - Beberapa kolom tanggal (birthdate, first_join_date, transaction_date, event_time)
     masih berupa objek dan perlu diubah menjadi datetime.
   - Kolom identitas yang kompleks akan dihapus atau diganti dengan fitur turunan (seperti usia).
   
Tahap visualisasi dan distribusi data akan dilakukan DEEP EDA setelah data digabungkan,
agar hubungan antara fitur dan variabel target (Churn) dapat diamati langsung..

##**BAGIAN 5**

**PRA-PEMROSESAN DATA (DATA PREPROCESSING)**

Tahap preprocessing bertujuan untuk membersihkan dan menyiapkan data
sebelum feature engineering. Langkah-langkah meliputi:
1. Konversi tipe data (datetime, category, numeric)
2. Penanganan missing values
3. Filter data transaksi (hanya status Success)
4. Penghapusan kolom yang tidak relevan untuk pemodelan
"""

# --- 5.1 Preprocessing Tabel Click Stream ---
print("=" * 60)
print("PREPROCESSING: TABEL CLICK STREAM")
print("=" * 60)

# Konversi tipe data
df_click_stream['event_time'] = pd.to_datetime(df_click_stream['event_time'])
# Ekstraksi atribut dari kolom JSON event_metadata (sangat cepat via regex)
metadata = df_click_stream['event_metadata']
df_click_stream['quantity'] = pd.to_numeric(metadata.str.extract(r'[\'"]quantity[\'"]\s*:\s*(\d+)', expand=False), errors='coerce')
df_click_stream['item_price'] = pd.to_numeric(metadata.str.extract(r'[\'"]item_price[\'"]\s*:\s*(\d+)', expand=False), errors='coerce')
df_click_stream['promo_amount'] = pd.to_numeric(metadata.str.extract(r'[\'"]promo_amount[\'"]\s*:\s*(\d+)', expand=False), errors='coerce')

df_click_stream['payment_status'] = metadata.str.extract(r'[\'"]payment_status[\'"]\s*:\s*[\'"]([^\'"]+)[\'"]', expand=False).astype('category')
df_click_stream['search_keywords'] = metadata.str.extract(r'[\'"]search_keywords[\'"]\s*:\s*[\'"]([^\'"]+)[\'"]', expand=False).astype('category')
df_click_stream['promo_code'] = metadata.str.extract(r'[\'"]promo_code[\'"]\s*:\s*[\'"]([^\'"]+)[\'"]', expand=False).astype('category')

# Lanjutan Konversi tipe data
df_click_stream['event_name'] = df_click_stream['event_name'].astype('category')
df_click_stream['traffic_source'] = df_click_stream['traffic_source'].astype('category')
df_click_stream['session_id'] = df_click_stream['session_id'].astype('string')
df_click_stream['event_id'] = df_click_stream['event_id'].astype('string')

print("✅ Konversi tipe data click_stream selesai.")
df_click_stream.info()

# --- 5.2 Preprocessing Tabel Customer ---
print("\n" + "=" * 60)
print("PREPROCESSING: TABEL CUSTOMER")
print("=" * 60)

# Konversi tipe data tanggal
df_customer['birthdate'] = pd.to_datetime(df_customer['birthdate'])
df_customer['first_join_date'] = pd.to_datetime(df_customer['first_join_date'])

# Feature engineering: umur dan durasi keanggotaan
current_year = datetime.now().year
current_date = datetime.now()
df_customer['age'] = current_year - df_customer['birthdate'].dt.year
df_customer['customer_duration'] = (current_date - df_customer['first_join_date']).dt.days
df_customer['customer_duration_year'] = df_customer['customer_duration'] / 365

# Konversi kolom kategorik
cat_cols = ['gender', 'device_type', 'home_location', 'home_country']
for col in cat_cols:
    df_customer[col] = df_customer[col].astype('category')

# Hapus kolom yang tidak diperlukan untuk pemodelan
# Justifikasi: kolom identitas (nama, email, username), lokasi spesifik,
# dan tanggal mentah tidak relevan untuk prediksi churn
df_customer.drop(columns=[
    'first_name', 'last_name', 'username', 'email',
    'device_id', 'birthdate', 'first_join_date',
    'home_location_lat', 'home_location_long',
    'home_location', 'home_country'
], inplace=True)

# Ekstraksi informasi versi OS: apakah menggunakan OS lama
# Justifikasi: pengguna OS lama cenderung memiliki pengalaman yang lebih buruk
df_customer['is_old_os'] = df_customer['device_version'].str.contains(
    r'Android 2|Android 3|OS 10|OS 11', na=False
).astype(int)
df_customer.drop(columns=['device_version'], inplace=True)

print("✅ Preprocessing tabel customer selesai.")
print(df_customer.head())

# --- 5.3 Preprocessing Tabel Transactions ---
print("\n" + "=" * 60)
print("PREPROCESSING: TABEL TRANSACTIONS")
print("=" * 60)

# Filter hanya transaksi berhasil (Success)
# Justifikasi: transaksi gagal tidak merepresentasikan perilaku pembelian
df_transactions = df_transactions[df_transactions['payment_status'] == 'Success']
print(f"Jumlah transaksi setelah filter: {len(df_transactions):,}")

# Handle missing values pada promo_code
df_transactions['promo_code'] = df_transactions['promo_code'].fillna('No Promo')

# Konversi tipe data tanggal dan numerik
df_transactions['created_at'] = pd.to_datetime(df_transactions['created_at'])
df_transactions['total_amount'] = pd.to_numeric(df_transactions['total_amount'])

print("✅ Preprocessing tabel transactions selesai.")

"""##**BAGIAN 6**
**FEATURE ENGINEERING**

Feature engineering merupakan tahap kritis dalam pipeline machine learning.
Pada tahap ini, kita mengkonstruksi fitur-fitur yang merepresentasikan
perilaku pelanggan dari tiga perspektif:

1. Fitur RFM (Recency, Frequency, Monetary) - dari tabel transactions
   - recency_days: jumlah hari sejak transaksi terakhir
   - frequency: jumlah transaksi
   - monetary_total: total nilai transaksi

2. Fitur Perilaku (Behavioral) - dari tabel click_stream
   - total_bookings, total_add_to_cart, total_searches, total_promos
   - conversion_rate: rasio booking terhadap total sesi

3. Fitur Sesi (Session-based) - dari tabel click_stream
   - total_sessions: jumlah sesi unik
   - customer_lifespan_days: rentang waktu aktivitas
   - main_traffic_source: sumber traffic dominan
"""

# --- 6.1 Click Stream Feature Engineering ---
print("=" * 60)
print("PREVENTION DATA LEAKAGE: APLIKASI CUT-OFF DATE")
print("=" * 60)

last_date = df_transactions['created_at'].max()
CUTOFF_DAYS = 90
cutoff_date = last_date - pd.Timedelta(days=CUTOFF_DAYS)

print(f"Data Terakhir     : {last_date}")
print(f"Tanggal Cut-off   : {cutoff_date} (90 hari sebelum akhir)")

# 1. Simpan Transaksi Masa Depan untuk Labeling Nanti
df_transactions_label = df_transactions[df_transactions['created_at'] >= cutoff_date].copy()

# 2. Batasi Data Transaksi dan Click Stream HANYA di Masa Lalu untuk Feature Engineering
df_transactions = df_transactions[df_transactions['created_at'] < cutoff_date].reset_index(drop=True)
df_click_stream = df_click_stream[df_click_stream['event_time'] < cutoff_date].reset_index(drop=True)

print(f"Valid Transaksi untuk Fitur   : {len(df_transactions):,} baris")
print(f"Valid Click Stream untuk Fitur : {len(df_click_stream):,} baris\n")

print("=" * 60)
print("FEATURE ENGINEERING: CLICK STREAM")
print("=" * 60)

# Binary encoding untuk tipe event
df_click_stream['is_booking'] = (df_click_stream['event_name'] == 'BOOKING').astype(int)
df_click_stream['is_add_to_cart'] = (df_click_stream['event_name'] == 'ADD_TO_CART').astype(int)
df_click_stream['is_search'] = (df_click_stream['event_name'] == 'SEARCH').astype(int)
df_click_stream['is_promo'] = (df_click_stream['event_name'] == 'ADD_PROMO').astype(int)

#Binary encoding untuk status pembayaran
# df_click_stream['is_failed_payment'] = (df_click_stream['payment_status'] == 'Failed').astype(int)
# df_click_stream['is_success_payment'] = (df_click_stream['payment_status'] == 'Success').astype(int)

# Agregasi ke level session
df_session = df_click_stream.groupby('session_id').agg({
    'is_booking': 'sum',
    'is_add_to_cart': 'sum',
    'is_search': 'sum',
    'is_promo': 'sum',
    'item_price': 'mean',
    'quantity': 'sum',
    'traffic_source': 'first',
}).reset_index()

print("✅ Agregasi click_stream ke level session selesai.")
print(df_session.head())

# --- 6.2 Transaction Feature Engineering (RFM) ---
print("\n" + "=" * 60)
print("FEATURE ENGINEERING: RFM DARI TRANSACTIONS")
print("=" * 60)

"""
Model RFM (Recency, Frequency, Monetary) adalah framework standar dalam
analisis perilaku pelanggan:
- Recency: Semakin baru transaksi terakhir, semakin aktif pelanggan
- Frequency: Semakin sering bertransaksi, semakin loyal pelanggan
- Monetary: Semakin besar nilai transaksi, semakin bernilai pelanggan

Catatan: recency_days sekarang dihitung murni menggunakan data sebelum
cut-off, sehingga aman dari data leakage.
"""

# Konversi tipe data transaksi
df_transactions['created_at'] = pd.to_datetime(df_transactions['created_at'])
df_transactions['total_amount'] = pd.to_numeric(df_transactions['total_amount'])

# Perhitungan reference date untuk recency
reference_date = df_transactions['created_at'].max()

# Agregasi RFM ke level customer
df_trx_agg = df_transactions.groupby('customer_id').agg(
    recency_days=('created_at', lambda x: (reference_date - x.max()).days),
    frequency=('session_id', 'nunique'),
    monetary_total=('total_amount', 'sum'),
    monetary_avg=('total_amount', 'mean'),
    fav_payment_method=('payment_method', lambda x: x.mode().iloc[0] if len(x.mode()) > 0 else 'Unknown'),
).reset_index()

print("✅ Agregasi transaksi (RFM) ke level customer selesai.")
print(df_trx_agg.head())

# --- 6.3 Session Aggregation ke Level Customer ---
print("\n" + "=" * 60)
print("FEATURE ENGINEERING: SESSION → CUSTOMER")
print("=" * 60)

"""
Agregasi data sesi ke level pelanggan memberikan gambaran holistik
tentang perilaku browsing masing-masing pelanggan.
"""

# Mapping session_id ke customer_id dari tabel transactions
session_customer_map = df_transactions[['session_id', 'customer_id']].drop_duplicates()

# Hitung session_start dan session_end dari click_stream
session_timing = df_click_stream.groupby('session_id').agg(
    session_start=('event_time', 'min'),
    session_end=('event_time', 'max'),
).reset_index()

# Merge session features dengan mapping dan timing
df_session_merged = df_session.merge(session_customer_map, on='session_id', how='inner')
df_session_merged = df_session_merged.merge(session_timing, on='session_id', how='left')

# Agregasi ke level customer
df_session_agg = df_session_merged.groupby('customer_id').agg(
    customer_lifespan_days=('session_start', lambda x: (x.max() - x.min()).days),
    total_bookings=('is_booking', 'sum'),
    total_add_to_cart=('is_add_to_cart', 'sum'),
    total_searches=('is_search', 'sum'),
    total_promos_viewed=('is_promo', 'sum'),
    avg_item_price=('item_price', 'mean'),
    total_quantity=('quantity', 'sum'),
    total_sessions=('session_id', 'nunique'),
    main_traffic_source=('traffic_source', lambda x: x.mode().iloc[0] if len(x.mode()) > 0 else 'Unknown'),
).reset_index()

# Hitung conversion rate (rasio booking per sesi)
df_session_agg['conversion_rate'] = np.where(
    df_session_agg['total_sessions'] > 0,
    df_session_agg['total_bookings'] / df_session_agg['total_sessions'],
    0
)

print("✅ Agregasi session ke level customer selesai.")
print(df_session_agg.head())

"""##**BAGIAN 7**
**INTEGRASI DATA & LABELING CHURN**

Pada tahap ini, ketiga sumber data digabungkan menjadi satu tabel master
dengan granularitas 1 baris = 1 pelanggan. Setelah integrasi, label churn
didefinisikan berdasarkan threshold recency.

Definisi Churn:
- Churn = 1: Pelanggan TIDAK bertransaksi dalam 90 hari terakhir
- Churn = 0: Pelanggan masih aktif (bertransaksi dalam 90 hari terakhir)

Pemilihan threshold 90 hari didasarkan pada:
- Siklus pembelian rata-rata pelanggan e-commerce
- Standar industri untuk definisi churn pada platform e-commerce
"""

# --- 7.1 Merge Tabel ---
print("=" * 60)
print("INTEGRASI DATA: MERGE KE TABEL MASTER")
print("=" * 60)

df_final = df_customer.merge(df_trx_agg, on='customer_id', how='left')
df_final = df_final.merge(df_session_agg, on='customer_id', how='left')

print(f"Shape setelah merge: {df_final.shape}")
print(f"Customer tanpa transaksi: {df_final['frequency'].isna().sum()}")

# Isi NaN numerik dengan 0 (customer tanpa transaksi/sesi)
numeric_cols = df_final.select_dtypes(include=['number']).columns
df_final[numeric_cols] = df_final[numeric_cols].fillna(0)

# Customer tanpa transaksi → recency diset ke nilai maksimum + 90
max_recency = df_final.loc[df_final['recency_days'] > 0, 'recency_days'].max()
df_final.loc[df_final['recency_days'] == 0, 'recency_days'] = max_recency + 90

# Isi NaN kategorikal
df_final['fav_payment_method'] = df_final['fav_payment_method'].astype(str).replace('nan', 'Unknown')
df_final['main_traffic_source'] = df_final['main_traffic_source'].astype(str).replace('nan', 'Unknown')

print(f"\nShape final: {df_final.shape}")
print(f"Kolom: {list(df_final.columns)}")
print(df_final.head())

# --- 7.2 Filter Customer dengan Transaksi ---
"""
Customer tanpa riwayat transaksi sama sekali dikeluarkan dari analisis
karena tidak memiliki sinyal perilaku yang cukup untuk prediksi churn.
"""
sebelum = len(df_final)
df_final = df_final[df_final['frequency'] > 0].reset_index(drop=True)
print(f"\nSebelum: {sebelum:,} → Sesudah: {len(df_final):,} (dibuang {sebelum - len(df_final):,})")

# --- 7.3 Labeling Churn ---
CHURN_THRESHOLD = 90

df_final['is_churn'] = (df_final['recency_days'] > CHURN_THRESHOLD).astype(int)

print("\n" + "=" * 40)
print("DISTRIBUSI CHURN")
print("=" * 40)
print(df_final['is_churn'].value_counts())
print(f"\nChurn Rate: {df_final['is_churn'].mean():.2%}")

# Visualisasi distribusi churn
fig, ax = plt.subplots(figsize=(5, 4))
colors = ['#2ecc71', '#e74c3c']
df_final['is_churn'].value_counts().plot(kind='bar', color=colors, edgecolor='black', ax=ax)
ax.set_xticklabels(['Active (0)', 'Churn (1)'], rotation=0)
ax.set_title('Distribusi Label Churn', fontsize=14, fontweight='bold')
ax.set_ylabel('Jumlah Customer')
for i, v in enumerate(df_final['is_churn'].value_counts().values):
    ax.text(i, v + 200, f'{v:,}', ha='center', fontweight='bold')
plt.tight_layout()
plt.show()

df_final.shape

df_final.columns

"""##**BAGIAN 8**
**EXPLORATORY DATA ANALYSIS (EDA) MENDALAM**

Tahap ini merupakan Deep EDA yang dilakukan SETELAH data dibersihkan
(cleaned), diagregasi, dan fitur-fitur baru diekstraksi.
Melakukan EDA pada tahap ini jauh lebih memberikan insight karena kita bisa
melihat pola dan hubungan langsung antara fitur-fitur final dengan label target (Churn).
"""

# 8.1 Distribusi Variabel Numerik terhadap Churn

print("\n➡️ Menggambar Distribusi Variabel Numerik berdasarkan Churn...")
# Memilih beberapa fitur numerik krusial
eda_num_features = ['age', 'customer_duration_year', 'frequency', 'monetary_total', 'total_sessions', 'total_bookings']
plot_cols = [col for col in eda_num_features if col in df_final.columns]

if plot_cols:
    n_cols = len(plot_cols)
    n_rows = (n_cols + 1) // 3
    fig, axes = plt.subplots(n_rows, 3, figsize=(14, 4 * n_rows))
    axes = axes.flatten() if n_cols > 1 else [axes]

    for i, col in enumerate(plot_cols):
        ax = axes[i]
        sns.histplot(data=df_final, x=col, hue='is_churn', kde=True,
                     palette=['#2ecc71', '#e74c3c'], ax=ax, bins=30, alpha=0.6)
        ax.set_title(f'Distribusi: {col}', fontsize=11, fontweight='bold')

    for j in range(i + 1, len(axes)):
        axes[j].set_visible(False)

    plt.suptitle('Distribusi Variabel Numerik berdasarkan Status Churn', fontsize=14, fontweight='bold', y=1.02)
    plt.tight_layout()
    plt.show()

# 8.2 Distribusi Variabel Kategorik terhadap Churn

print("\n➡️ Menggambar Distribusi Variabel Kategorik berdasarkan Churn...")
eda_cat_features = ['fav_payment_method', 'main_traffic_source', 'is_old_os']
plot_cat_cols = [col for col in eda_cat_features if col in df_final.columns]

if plot_cat_cols:
    fig, axes = plt.subplots(1, len(plot_cat_cols), figsize=(6 * len(plot_cat_cols), 5))
    axes = [axes] if len(plot_cat_cols) == 1 else axes

    for i, col in enumerate(plot_cat_cols):
        ax = axes[i]
        sns.countplot(data=df_final, x=col, hue='is_churn', palette=['#2ecc71', '#e74c3c'], ax=ax, edgecolor='black')
        ax.set_title(f'Churn berdasarkan {col}', fontsize=12, fontweight='bold')
        ax.tick_params(axis='x', rotation=45)

    plt.tight_layout()
    plt.show()

# 8.3 Boxplot Outlier & Deteksi Multikolinearitas (Korelasi)

print("\n➡️ Deteksi Outlier pada Tabel Final...")
# 1. Boxplot Outlier
numeric_features_to_plot = ['recency_days', 'frequency', 'monetary_total', 'customer_duration_year', 'total_sessions']
fig, axes = plt.subplots(1, len(numeric_features_to_plot), figsize=(16, 5))
for i, col in enumerate(numeric_features_to_plot):
    if col in df_final.columns:
        bp = axes[i].boxplot(df_final[col].dropna(), patch_artist=True, vert=True)
        bp['boxes'][0].set_facecolor('#9b59b6')
        bp['boxes'][0].set_alpha(0.7)
        axes[i].set_title(f'{col}', fontsize=10, fontweight='bold')

        Q1 = df_final[col].quantile(0.25)
        Q3 = df_final[col].quantile(0.75)
        IQR = Q3 - Q1
        outlier_count = ((df_final[col] < Q1 - 1.5 * IQR) | (df_final[col] > Q3 + 1.5 * IQR)).sum()
        axes[i].set_xlabel(f'Outliers: {outlier_count:,}', fontsize=9, color='red')

plt.suptitle('Sebaran Outlier pada Fitur Utama', fontsize=14, fontweight='bold', y=1.05)
plt.tight_layout()
plt.show()

# # 2. Correlation Heatmap
# print("\n➡️ Menggambar Heatmap Korelasi...")
# master_numeric = df_final.select_dtypes(include=['number']).drop(columns=['customer_id', 'is_churn', 'recency_days'], errors='ignore')

# if len(master_numeric.columns) > 1:
#     corr_matrix = master_numeric.corr()

#     fig, ax = plt.subplots(figsize=(14, 11))
#     mask = np.triu(np.ones_like(corr_matrix, dtype=bool))
#     sns.heatmap(corr_matrix, mask=mask, annot=True, fmt='.2f', cmap='coolwarm',
#                 center=0, vmin=-1, vmax=1, square=True, linewidths=0.5,
#                 ax=ax, annot_kws={"size": 8.5})
#     ax.set_title('Correlation Heatmap — Fitur Model Utama', fontsize=16, fontweight='bold')
#     plt.tight_layout()
#     plt.show()

#     high_corr = []
#     for i in range(len(corr_matrix.columns)):
#         for j in range(i + 1, len(corr_matrix.columns)):
#             if abs(corr_matrix.iloc[i, j]) > 0.8:
#                 high_corr.append((corr_matrix.columns[i], corr_matrix.columns[j],
#                                   round(corr_matrix.iloc[i, j], 3)))

#     if high_corr:
#         print("\n⚠️ Pasangan fitur dengan korelasi positif/negatif tinggi (|r| > 0.8) terdeteksi:")
#         for f1, f2, r in high_corr:
#             print(f"   {f1} ↔ {f2}: r = {r}")
#         print("   → Catatan: Karena algoritma yang digunakan adalah ensemble berbasis Tree (XGBoost & Random Forest),")
#         print("     model bersifat ROBUST (kebal) terhadap efek multikolinearitas.")
#     else:
#         print("\n✅ Tidak ditemukan multikolinearitas ekstrim.")

"""##**BAGIAN 9**

**PERSIAPAN DATA UNTUK PEMODELAN**

Persiapan data meliputi:
1. Seleksi fitur (menghapus identifier dan variabel berisiko leakage)
2. Encoding variabel kategorik (One-Hot Encoding)
3. Pembagian data train-test (80:20, stratified)
4. Standarisasi fitur numerik

PENTING - Pencegahan Data Leakage:
Variabel 'recency_days' DIHAPUS dari fitur model karena label churn
didefinisikan langsung dari variabel ini (churn = recency > 90 hari).
Menyertakan recency sebagai fitur akan menyebabkan model "curang"
dan menghasilkan performa artifisial yang tinggi.
"""

print("=" * 60)
print("PERSIAPAN DATA UNTUK PEMODELAN")
print("=" * 60)

# Hapus kolom yang tidak boleh menjadi fitur
# - customer_id: identifier, bukan fitur prediktif
# - recency_days: POTENSI DATA LEAKAGE (definisi churn berbasis recency)
df_model = df_final.drop(columns=['customer_id', 'recency_days'])

# One-Hot Encoding untuk variabel kategorik
cat_cols_model = df_model.select_dtypes(include=['category', 'object']).columns.tolist()
if 'is_churn' in cat_cols_model:
    cat_cols_model.remove('is_churn')

df_model = pd.get_dummies(df_model, columns=cat_cols_model, drop_first=True)
print(f"\nJumlah fitur setelah encoding: {df_model.shape[1] - 1}")
print(f"Fitur: {[c for c in df_model.columns if c != 'is_churn']}")

# Pisahkan fitur (X) dan target (y)
X = df_model.drop(columns=['is_churn'])
y = df_model['is_churn']

# Pembagian data train-test
# Stratified split menjamin proporsi churn yang sama di train dan test
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

print(f"\nTrain set: {X_train.shape[0]:,} sampel")
print(f"Test set : {X_test.shape[0]:,} sampel")
print(f"Proporsi churn di train: {y_train.mean():.2%}")
print(f"Proporsi churn di test : {y_test.mean():.2%}")

# Standarisasi fitur
# Justifikasi: Meskipun XGBoost berbasis tree dan tidak memerlukan
# standarisasi, namun hal ini membantu interpretasi SHAP values
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

print("\n✅ Persiapan data selesai!")

"""##**BAGIAN 10**
**PEMODELAN & PELATIHAN MODEL**

Pada tahap ini, tiga algoritma klasifikasi dilatih dan dibandingkan:

1. Logistic Regression (Baseline)
   - Model linear paling sederhana untuk klasifikasi biner
   - Berfungsi sebagai baseline: jika model lain tidak jauh lebih baik,
     maka model yang lebih kompleks tidak diperlukan

2. Random Forest
   - Ensemble berbasis bagging (Bootstrap Aggregating)
   - Membangun banyak pohon keputusan secara paralel dan independen
   - Robust terhadap overfitting karena averaging

3. XGBoost (Extreme Gradient Boosting) → MODEL UTAMA
   - Ensemble berbasis boosting (sekuensial, bukan paralel)
   - Setiap pohon baru memperbaiki error dari pohon sebelumnya
   - Memiliki regularisasi (L1, L2) untuk mencegah overfitting
   - Kompatibel dengan SHAP untuk analisis XAI

Perbandingan ini bertujuan memberikan justifikasi empiris mengapa
XGBoost dipilih sebagai model utama untuk analisis XAI.

Penanganan Class Imbalance:
- Logistic Regression & Random Forest: class_weight='balanced'
- XGBoost: scale_pos_weight = n_negatif / n_positif
"""

print("=" * 60)
print("PELATIHAN & PERBANDINGAN MODEL")
print("=" * 60)

# Hitung class weight untuk menangani imbalance
neg_count = (y_train == 0).sum()
pos_count = (y_train == 1).sum()
scale_pos = neg_count / pos_count

print(f"Active (0): {neg_count:,}")
print(f"Churn  (1): {pos_count:,}")
print(f"Rasio imbalance: {scale_pos:.4f}")

# --- 10.1 Logistic Regression (Baseline) ---
print("\n" + "-" * 40)
print("Model 1: Logistic Regression (Baseline)")
print("-" * 40)
model_lr = LogisticRegression(
    max_iter=1000,
    class_weight='balanced',
    random_state=42
)
model_lr.fit(X_train_scaled, y_train)
print("✅ Logistic Regression selesai dilatih.")

# --- 10.2 Random Forest ---
print("\n" + "-" * 40)
print("Model 2: Random Forest")
print("-" * 40)
model_rf = RandomForestClassifier(
    n_estimators=300,
    max_depth=10,
    class_weight='balanced',
    random_state=42,
    n_jobs=-1
)
model_rf.fit(X_train_scaled, y_train)
print("✅ Random Forest selesai dilatih.")

# --- 10.3 XGBoost (Model Utama) ---
print("\n" + "-" * 40)
print("Model 3: XGBoost (Model Utama)")
print("-" * 40)
model_xgb = XGBClassifier(
    n_estimators=300,
    max_depth=6,
    learning_rate=0.1,
    scale_pos_weight=scale_pos,
    eval_metric='auc',
    random_state=42,
    use_label_encoder=False,
)
model_xgb.fit(X_train_scaled, y_train)
print("✅ XGBoost selesai dilatih.")

print("\n✅ Semua model berhasil dilatih!")

"""##**BAGIAN 11**
**EVALUASI & PERBANDINGAN MODEL**

Pada bagian ini, fokus utama adalah mengevaluasi kinerja model-model klasifikasi yang telah dibangun dan membandingkan performa antara Logistic Regression, Random Forest, serta XGBoost. Evaluasi ini krusial untuk mengidentifikasi model terbaik yang akan digunakan untuk analisis Explainable AI (XAI) lebih lanjut.

Evaluasi dilakukan menggunakan multiple metrics untuk memberikan
gambaran komprehensif tentang performa setiap model:

1. Accuracy: proporsi prediksi yang benar secara keseluruhan
2. Precision: dari semua prediksi churn, berapa yang benar-benar churn
3. Recall: dari semua customer churn, berapa yang berhasil terdeteksi
4. F1-Score: harmonic mean dari precision dan recall
5. ROC-AUC: kemampuan model membedakan antara kelas positif dan negatif

Catatan penting:
- Pada konteks churn prediction, RECALL pada kelas Churn sangat penting
  karena kita ingin meminimalkan kasus churn yang tidak terdeteksi
  (false negative = customer churn yang lolos tanpa intervensi)
- Perbandingan antar model menunjukkan justifikasi empiris pemilihan
  XGBoost sebagai model utama untuk analisis XAI
"""

print("=" * 60)
print("EVALUASI & PERBANDINGAN MODEL")
print("=" * 60)

# --- 11.1 Hitung Metrik Semua Model ---
models = {
    'Logistic Regression': model_lr,
    'Random Forest': model_rf,
    'XGBoost': model_xgb,
}

results = []
roc_data = {}  # untuk plot ROC overlay

for name, model in models.items():
    y_pred_m = model.predict(X_test_scaled)
    y_proba_m = model.predict_proba(X_test_scaled)[:, 1]

    acc_m = accuracy_score(y_test, y_pred_m)
    prec_m = precision_score(y_test, y_pred_m)
    rec_m = recall_score(y_test, y_pred_m)
    f1_m = f1_score(y_test, y_pred_m)
    auc_m = roc_auc_score(y_test, y_proba_m)

    results.append({
        'Model': name,
        'Accuracy': round(acc_m, 4),
        'Precision': round(prec_m, 4),
        'Recall': round(rec_m, 4),
        'F1-Score': round(f1_m, 4),
        'ROC-AUC': round(auc_m, 4),
    })

    # Simpan data ROC
    fpr_m, tpr_m, _ = roc_curve(y_test, y_proba_m)
    roc_data[name] = (fpr_m, tpr_m, auc_m)

df_results = pd.DataFrame(results)

print("\n TABEL PERBANDINGAN PERFORMA MODEL")
print("=" * 70)
print(df_results.to_string(index=False))
print("=" * 70)

# Identifikasi model terbaik berdasarkan ROC-AUC
best_model_name = df_results.loc[df_results['ROC-AUC'].idxmax(), 'Model']
print(f"\n Model terbaik berdasarkan ROC-AUC: {best_model_name}")

# --- 11.2 Visualisasi Perbandingan Metrik (Bar Chart) ---
fig, ax = plt.subplots(figsize=(12, 6))

metrics_to_plot = ['Accuracy', 'Precision', 'Recall', 'F1-Score', 'ROC-AUC']
x = np.arange(len(metrics_to_plot))
width = 0.25
colors = ['#3498db', '#2ecc71', '#e74c3c']

for i, (_, row) in enumerate(df_results.iterrows()):
    values = [row[m] for m in metrics_to_plot]
    bars = ax.bar(x + i * width, values, width, label=row['Model'], color=colors[i],
                  edgecolor='black', alpha=0.85)
    # Label di atas bar
    for bar, val in zip(bars, values):
        ax.text(bar.get_x() + bar.get_width()/2, bar.get_height() + 0.005,
                f'{val:.3f}', ha='center', va='bottom', fontsize=8, fontweight='bold')

ax.set_xticks(x + width)
ax.set_xticklabels(metrics_to_plot, fontsize=11)
ax.set_ylim(0, 1.08)
ax.set_ylabel('Skor', fontsize=12)
ax.set_title('Perbandingan Performa Model', fontsize=14, fontweight='bold')
ax.legend(fontsize=11)
ax.grid(axis='y', alpha=0.3)
plt.tight_layout()
plt.show()

# --- 11.3 ROC Curve Overlay (Semua Model) ---
fig, ax = plt.subplots(figsize=(8, 6))

roc_colors = {'Logistic Regression': '#3498db', 'Random Forest': '#2ecc71', 'XGBoost': '#e74c3c'}
for name, (fpr_m, tpr_m, auc_m) in roc_data.items():
    ax.plot(fpr_m, tpr_m, color=roc_colors[name], lw=2.5,
            label=f'{name} (AUC = {auc_m:.4f})')

ax.plot([0, 1], [0, 1], 'k--', lw=1, alpha=0.5, label='Random (AUC = 0.5)')
ax.set_title('Perbandingan ROC Curve — Semua Model', fontsize=14, fontweight='bold')
ax.set_xlabel('False Positive Rate', fontsize=12)
ax.set_ylabel('True Positive Rate', fontsize=12)
ax.legend(fontsize=10, loc='lower right')
ax.grid(alpha=0.3)
plt.tight_layout()
plt.show()

# --- 11.4 Detail Evaluasi XGBoost (Model Utama) ---
"""
Karena XGBoost terbukti sebagai model dengan performa terbaik,
berikut adalah detail evaluasi lengkap untuk model utama.
Model inilah yang akan digunakan untuk analisis XAI pada BAB 10.
"""
print("\n" + "=" * 60)
print("DETAIL EVALUASI — XGBOOST (MODEL UTAMA)")
print("=" * 60)

y_pred = model_xgb.predict(X_test_scaled)
y_proba = model_xgb.predict_proba(X_test_scaled)[:, 1]

print(classification_report(y_test, y_pred, target_names=['Active', 'Churn']))

# Confusion Matrix XGBoost
fig, ax = plt.subplots(figsize=(6, 5))
cm = confusion_matrix(y_test, y_pred)
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues',
            xticklabels=['Active', 'Churn'],
            yticklabels=['Active', 'Churn'],
            ax=ax, annot_kws={"size": 16})
ax.set_title('Confusion Matrix — XGBoost', fontsize=14, fontweight='bold')
ax.set_ylabel('Actual', fontsize=12)
ax.set_xlabel('Predicted', fontsize=12)
plt.tight_layout()
plt.show()

# --- 11.5 Cross Validation (5-Fold) ---
"""
Stratified K-Fold Cross Validation digunakan untuk memvalidasi bahwa
performa model konsisten dan bukan hasil kebetulan dari satu split
tertentu. Stratified menjamin proporsi churn sama di setiap fold.
"""
print("\n" + "=" * 60)
print("CROSS VALIDATION (5-FOLD STRATIFIED)")
print("=" * 60)

skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)

for name, model in models.items():
    cv_auc = cross_val_score(model, X_train_scaled, y_train, cv=skf, scoring='roc_auc')
    cv_f1 = cross_val_score(model, X_train_scaled, y_train, cv=skf, scoring='f1')
    print(f"\n{name}:")
    print(f"  ROC-AUC : {cv_auc.mean():.4f} ± {cv_auc.std():.4f}  {list(cv_auc.round(4))}")
    print(f"  F1-Score: {cv_f1.mean():.4f} ± {cv_f1.std():.4f}  {list(cv_f1.round(4))}")

print("\nCross Validation selesai.")
print("→ Standar deviasi rendah menunjukkan model stabil dan tidak overfit.")
print("→ XGBoost dipilih sebagai model utama untuk analisis XAI")

"""##**BAGIAN 12 & 13**
**DEPLOYMENT: ANALISIS XAI DENGAN SHAP DAN REKOMENDASI BISNIS**

Fase ini merupakan implementasi dari tahap **Deployment** dalam kerangka CRISP-DM, dengan fokus pada penerjemahan output model prediktif ke dalam insight yang actionable. Tahap ini terbagi menjadi dua komponen utama:

1.  **Analisis XAI dengan SHAP (Bagian 12):** Mengeksplorasi dan memahami bagaimana model XGBoost membuat prediksinya menggunakan metode SHAP untuk mengidentifikasi fitur-fitur pendorong churn.
2.  **Rekomendasi Bisnis Berbasis Analisis SHAP (Bagian 13):** Merumuskan strategi dan inisiatif bisnis yang konkret berdasarkan insight yang diperoleh dari analisis SHAP, bertujuan untuk mitigasi churn dan peningkatan retensi pelanggan.

Setelah membangun dan mengevaluasi model prediksi churn, langkah selanjutnya adalah menerjemahkan hasil model menjadi insight yang dapat digunakan secara bisnis. Bagian ini berfokus pada penggunaan Explainable AI (XAI), khususnya SHAP, untuk memahami faktor-faktor pendorong churn dan merumuskan rekomendasi strategi mitigasi yang efektif.

SHAP (SHapley Additive exPlanations) adalah metode interpretasi model
berbasis game theory yang memberikan kontribusi marginal setiap fitur
terhadap prediksi model.

Keunggulan SHAP dibandingkan metode XAI lainnya:
1. Konsisten secara matematis (berdasarkan Shapley values)
2. Memberikan interpretasi lokal (per instance) DAN global (keseluruhan)
3. Kompatibel dengan berbagai jenis model, termasuk XGBoost

Analisis yang dilakukan:
1. SHAP Summary Plot (Beeswarm): visualisasi distribusi SHAP values
   untuk semua fitur dan semua instance
2. SHAP Bar Plot: rata-rata absolute SHAP values per fitur (global importance)
3. SHAP Waterfall Plot: penjelasan prediksi untuk satu instance tertentu
4. SHAP Dependence Plot: hubungan antara nilai fitur dan SHAP value
"""

print("=" * 60)
print("ANALISIS EXPLAINABLE AI (XAI) DENGAN SHAP")
print("=" * 60)

# Inisialisasi SHAP Explainer
explainer = shap.TreeExplainer(model_xgb)
shap_values = explainer.shap_values(X_test_scaled)

# Buat DataFrame SHAP untuk interpretasi
shap_df = pd.DataFrame(
    shap_values,
    columns=X.columns,
    index=X_test.index
)

print(f"\nShape SHAP values: {shap_values.shape}")
print(f"Jumlah fitur: {len(X.columns)}")

# --- 12.1 SHAP Summary Plot (Beeswarm) ---
"""
Summary Plot memberikan gambaran global tentang:
- Fitur mana yang paling berpengaruh (urutan dari atas ke bawah)
- Arah pengaruh setiap fitur (warna: merah = nilai tinggi, biru = nilai rendah)
- Besaran pengaruh (posisi horizontal: kanan = mendorong prediksi churn)
"""
print("\n--- SHAP Summary Plot (Beeswarm) ---")
shap.summary_plot(shap_values, X_test_scaled,
                  feature_names=X.columns.tolist(),
                  show=True)

# --- 12.2 SHAP Bar Plot (Global Feature Importance) ---
"""
Bar Plot menunjukkan rata-rata absolute SHAP value untuk setiap fitur,
memberikan ranking fitur berdasarkan kontribusi rata-rata terhadap prediksi.
"""
print("\n--- SHAP Bar Plot (Feature Importance) ---")
shap.summary_plot(shap_values, X_test_scaled,
                  feature_names=X.columns.tolist(),
                  plot_type='bar',
                  show=True)

# --- 12.3 SHAP Waterfall Plot (Local Explanation) ---
"""
Waterfall Plot menjelaskan bagaimana model sampai pada prediksi tertentu
untuk satu customer spesifik. Setiap bar menunjukkan kontribusi satu fitur
terhadap prediksi akhir, dimulai dari base value (rata-rata prediksi).
"""
print("\n--- SHAP Waterfall Plot (Contoh 1 Customer) ---")
shap.plots.waterfall(
    shap.Explanation(
        values=shap_values[0],
        base_values=explainer.expected_value,
        data=X_test_scaled[0],
        feature_names=X.columns.tolist()
    ),
    show=True
)

"""### **12.5 SHAP Dependence Plot (Feature Interaction)**

SHAP Dependence Plot menunjukkan bagaimana nilai suatu fitur memengaruhi kontribusinya terhadap prediksi model, dan dapat mengungkapkan interaksi antara dua fitur. Misalnya, bagaimana efek `customer_duration` terhadap churn bisa berubah tergantung pada `frequency`.
"""

print('\n--- SHAP Dependence Plot (Interaksi Fitur) ---')

feature_importance = pd.DataFrame({
    'feature': X.columns.tolist(),
    'importance': np.abs(shap_values).mean(axis=0)
}).sort_values(by='importance', ascending=False).reset_index(drop=True)
# Memilih dua fitur teratas dari Top Feature Analysis untuk dianalisis interaksinya
feature_1 = feature_importance['feature'].iloc[0] # customer_duration
feature_2 = feature_importance['feature'].iloc[1] # frequency
fig, ax = plt.subplots(figsize=(10, 6))
shap.dependence_plot(
    feature_1,
    shap_values,
    X_test_scaled,
    feature_names=X.columns.tolist(),
    interaction_index=feature_2, # Menunjukkan interaksi dengan fitur kedua
    show=False,
    ax=ax
)
ax.set_title(f'SHAP Dependence Plot: {feature_1} vs SHAP Value (Interaksi dengan {feature_2})', fontsize=14, fontweight='bold')
ax.set_xlabel(f'Nilai Fitur {feature_1}')
ax.set_ylabel(f'SHAP Value untuk {feature_1}')
plt.tight_layout()
plt.show()

# shap.dependence_plot("total_quantity", shap_values, X_test_scaled, feature_names=X.columns.tolist(), interaction_index=None)

"""##**BAGIAN 13**
**REKOMENDASI BISNIS BERBASIS ANALISIS SHAP**

**13.1 Customer Duration (Pengaruh Tertinggi — Tinggi → Churn)**

Pelanggan dengan durasi keanggotaan yang panjang justru lebih berisiko churn. Ini mengindikasikan adanya customer fatigue — pelanggan lama yang tidak lagi mendapatkan nilai baru dari platform cenderung berhenti bertransaksi.
Rekomendasi: Buat program loyalitas berjenjang (tiered loyalty program) yang memberikan benefit eksklusif bagi pelanggan dengan durasi keanggotaan > 1 tahun, seperti early access produk baru, cashback khusus member lama, atau personalized offer berbasis riwayat pembelian.

**13.2 Frequency (Rendah → Churn)**

Frekuensi transaksi yang rendah adalah sinyal kuat bahwa pelanggan mulai kehilangan keterlibatan dengan platform. Pelanggan yang jarang bertransaksi memiliki risiko churn yang signifikan lebih tinggi.
Rekomendasi: Terapkan triggered campaign berbasis inaktivitas — kirimkan notifikasi atau email otomatis kepada pelanggan yang tidak bertransaksi dalam 30–60 hari dengan insentif pembelian (voucher terbatas waktu). Segmen ini adalah prioritas utama untuk program win-back.

**13.3 Customer Lifespan Days (Rendah → Churn)**

Pelanggan dengan rentang aktivitas browsing yang pendek — artinya mereka hanya aktif dalam periode singkat — sangat rentan churn. Ini menunjukkan kegagalan onboarding atau kurangnya engagement di awal penggunaan.
Rekomendasi: Perkuat proses onboarding untuk pelanggan baru: berikan panduan fitur platform, welcome offer yang menarik di 30 hari pertama, dan pastikan pengalaman pertama berbelanja berjalan lancar untuk membangun kebiasaan transaksi sejak dini.

**13.4 Monetary Total (Rendah → Churn)**

Pelanggan dengan total nilai transaksi rendah lebih berisiko churn. Mereka kemungkinan belum menemukan produk yang relevan atau belum merasakan value proposition platform secara penuh.
Rekomendasi: Gunakan product recommendation engine berbasis riwayat browsing (click stream) untuk meningkatkan relevansi produk yang ditampilkan. Pelanggan dengan monetary rendah juga dapat dijadikan target upselling dengan produk di kisaran harga yang sudah pernah mereka lihat.

**13.5 Total Quantity (Rendah → Churn)**

Temuan ini cukup menarik dan berlawanan dengan intuisi: pelanggan yang membeli dalam jumlah banyak (quantity per transaksi tinggi) justru cenderung churn. Kemungkinan interpretasinya adalah pelanggan yang melakukan pembelian dalam jumlah besar sekali waktu (bulk buyer) tidak kembali lagi setelahnya karena kebutuhannya sudah terpenuhi.
Rekomendasi: Untuk segmen bulk buyer, rancang strategi retensi berbasis siklus pembelian — estimasikan kapan stok mereka habis dan kirimkan reminder pembelian ulang sebelum periode tersebut. Program subscription atau berlangganan rutin juga dapat dipertimbangkan untuk segmen ini.
"""